import { handleLeadRequest } from "@/lib/lead-routing";

export const runtime = "nodejs";

const industryConfig = {
  therapists: {
    routeName: "industry-audit-therapists",
    webhookEnvVar: "N8N_THERAPISTS_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "practiceName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "providerCount",
      "ehrTools",
      "adminPain",
      "monthlyVolume",
      "phiAcknowledgement",
      "contactConsent",
    ],
  },
  "dental-practices": {
    routeName: "industry-audit-dental-practices",
    webhookEnvVar: "N8N_DENTAL_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "practiceName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "providerCount",
      "monthlyPatientVolume",
      "currentTools",
      "biggestLeak",
      "phiAcknowledgement",
      "contactConsent",
    ],
  },
  "hvac-contractors": {
    routeName: "industry-audit-hvac-contractors",
    webhookEnvVar: "N8N_HVAC_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "companyName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "serviceArea",
      "monthlyLeadVolume",
      "afterHoursCoverage",
      "currentTools",
      "biggestLeak",
      "dataAcknowledgement",
      "contactConsent",
    ],
  },
  "plumbing-contractors": {
    routeName: "industry-audit-plumbing-contractors",
    webhookEnvVar: "N8N_PLUMBING_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "companyName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "serviceArea",
      "monthlyLeadVolume",
      "afterHoursCoverage",
      "currentTools",
      "biggestLeak",
      "dataAcknowledgement",
      "contactConsent",
    ],
  },
  "roofing-contractors": {
    routeName: "industry-audit-roofing-contractors",
    webhookEnvVar: "N8N_ROOFING_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "companyName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "serviceArea",
      "monthlyLeadVolume",
      "stormLeadSource",
      "currentTools",
      "biggestLeak",
      "dataAcknowledgement",
      "contactConsent",
    ],
  },
  "postal-presort": {
    routeName: "industry-audit-postal-presort",
    webhookEnvVar: "N8N_POSTAL_PRESORT_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "companyName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "monthlyPieceVolume",
      "mailClassMix",
      "currentMailPrep",
      "workshareInterest",
      "phiStatus",
      "biggestPain",
      "dataAcknowledgement",
      "contactConsent",
    ],
  },
  "legal-intake": {
    routeName: "industry-audit-legal-intake",
    webhookEnvVar: "N8N_LEGAL_INTAKE_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "firmName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "practiceAreas",
      "attorneyCount",
      "monthlyInquiryVolume",
      "caseManagementSystem",
      "biggestPain",
      "ethicsAcknowledgement",
      "contactConsent",
    ],
  },
  "home-services": {
    routeName: "industry-audit-home-services",
    webhookEnvVar: "N8N_HOME_SERVICES_AUDIT_WEBHOOK_URL",
    requiredFields: [
      "vertical",
      "companyName",
      "contactName",
      "workEmail",
      "workPhone",
      "website",
      "serviceArea",
      "subVertical",
      "monthlyLeadVolume",
      "afterHoursCoverage",
      "currentTools",
      "biggestLeak",
      "dataAcknowledgement",
      "contactConsent",
    ],
  },
} as const;

export async function POST(request: Request) {
  return handleLeadRequest(request, (body) => {
    const vertical = typeof body.vertical === "string" ? body.vertical : "";
    return industryConfig[vertical as keyof typeof industryConfig] ?? null;
  });
}

